name: Chart Validate Pull Request
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "HMCTS Github"

jobs:
  - job: Validate
    steps:
      - template: jobs/charts/validate.yaml@cnp-library
        parameters:
          chartName: nodejs
          chartReleaseName: chart-nodejs-ci-test
          chartNamespace: chart-tests

  - job: Release
    dependsOn: Validate
    # If there is a tag, create a release
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
      - template: jobs/charts/release.yaml@cnp-library
        parameters:
          chartName: nodejs
          chartReleaseName: chart-nodejs
          chartNamespace: chart-tests
