name: Chart Validate Pull Request
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/stepify-jobs
      endpoint: "HMCTS Github"

jobs:
  - job: Validate
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: step/validate.yaml@cnp-library
        parameters:
          chartName: nodejs
          chartReleaseName: chart-nodejs-ci-test
          chartNamespace: chart-tests

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
      - template: jobs/charts/release.yaml@cnp-library
        parameters:
          chartName: nodejs
          chartReleaseName: chart-nodejs
          chartNamespace: chart-tests
