name: Nodejs Chart CI Pipeline

variables:
  vmImage: "Ubuntu 16.04"
  chartname: nodejs
  chartNamespace: chart-tests

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: cnp-library
      type: github
      name: hmcts/cnp-azuredevops-libraries
      ref: refs/heads/stepify-jobs
      endpoint: "HMCTS Github"

jobs:
  - job: Validate
    pool:
      vmImage: $(vmImage)
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartNamespace: $(chartNamespace)
          chartName: $(chartname)
          chartReleaseName: chart-nodejs-ci-test

  - job: Release
    # Make sure we are on the master branch with a tag
    # to trigger this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
    dependsOn: Validate
    pool:
      vmImage: $(vmImage)
    steps:
      - template: steps/charts/release.yaml@cnp-library
        parameters:
          chartNamespace: $(chartNamespace)
          chartName: $(chartname)
          chartReleaseName: chart-nodejs
