image: hmcts.azurecr.io/hmcts/custard-frontend
ingressHost: chart-nodejs.service.core-compute-preview.internal
environment:
  REFORM_TEAM: cnp
  REFORM_SERVICE_NAME: rhubarb-frontend
  REFORM_ENVIRONMENT: preview
configmap:
  VAR_A: VALUE_A
  VAR_B: VALUE_B
